### ISSUE TITLE
How to create table with no geometry Column

### ISSUE THREAD

**Issue by Reed-Xiong** [ngageoint/geopackage-android#36]
Hi guy
I am a new for  geopackage,I wanna create a new table with no  geometry Column,but I am failed finally. so please give me some ideas to deal with it . I have done something in activity as bellow

 I got the object by "GeoPackager geopackager=GeoPackageFactory.getManager(this);" and create table by 
createFeatureTable() or createFeatureTableWithMetadata(), but is invalid with exception that "no GEOEMTRY column was found for table 'my_table'"

**Comment by bosborn** [comment]
[Feature tables](http://www.geopackage.org/spec/#feature_user_tables) are meant for spatial data and require the geometry column.  Alternatively look into making an [Attributes table](http://www.geopackage.org/spec/#attributes).  That should accommodate whatever you are trying to accomplish.  GeoPackages are SQLite files so you can also create your own custom tables, but they would not be easily discoverable or usable without an extension.

Attributes example:
```
List<AttributesColumn> columns = new ArrayList<AttributesColumn>();

columns.add(AttributesColumn.createColumn(1, "test_text",
    GeoPackageDataType.TEXT, false, ""));
columns.add(AttributesColumn.createColumn(2, "test_real",
    GeoPackageDataType.REAL, false, null));
columns.add(AttributesColumn.createColumn(3, "test_boolean",
    GeoPackageDataType.BOOLEAN, false, null));
columns.add(AttributesColumn.createColumn(4, "test_blob",
    GeoPackageDataType.BLOB, false, null));
columns.add(AttributesColumn.createColumn(5, "test_integer",
    GeoPackageDataType.INTEGER, false, null));
columns.add(AttributesColumn.createColumn(6, "test_text_limited",
    GeoPackageDataType.TEXT, 5L, false, null));
columns.add(AttributesColumn.createColumn(7, "test_blob_limited",
    GeoPackageDataType.BLOB, 200L, false, null));

AttributesTable attributesTable = geoPackage
    .createAttributesTableWithId("test_attributes", columns);
Contents attributesContents = attributesTable.getContents();

AttributesDao attributesDao = geoPackage
    .getAttributesDao(attributesTable.getTableName());

// Insert one row
AttributesRow newRow = attributesDao.newRow();
for (AttributesColumn column : attributesTable.getColumns()) {
    // TODO Set values...
    // newRow.setValue(column.getName(), value);
}
long rowId = attributesDao.create(newRow);
```
