### ISSUE TITLE
Failed to use Custom coordinate system

### ISSUE THREAD

**Issue by sunshine0576** [ngageoint/geopackage-android#38]
#### Version Information:

  * GeoPackage Android Version:  mil.nga.geopackage:geopackage-android:1.3.2

#### Expected Results:

I want to use my own coordinatesystem，for example:
+proj=tmerc +lat_0=0 +lon_0=121 +k=1 +x_0=500000 +y_0=0 +ellps=krass +units=m +no_defs

srs_id,srs_name,srs_id,organization,organization_coordsys_id,definition,description
100001,unnamed,100001,NONE,100001,"PROJCS[""unnamed"",GEOGCS[""Krassovsky, 1942"",DATUM[""unknown"",SPHEROID[""krass"",6378245,298.3]],PRIMEM[""Greenwich"",0],UNIT[""degree"",0.0174532925199433]],PROJECTION[""Transverse_Mercator""],PARAMETER[""latitude_of_origin"",0],PARAMETER[""central_meridian"",121],PARAMETER[""scale_factor"",1],PARAMETER[""false_easting"",500000],PARAMETER[""false_northing"",0],UNIT[""Meter"",1]]",

#### Observed Results:
package mil.nga.geopackage.features.user;
class FeatureDao 

   projection = ProjectionFactory.getProjection(geometryColumns.getSrs());

#### Output:

Failed to create project for EPSG 100001 Parrameters:null.

#### Additional Information:
Resolvent：

    try {
            projection = ProjectionFactory.getProjection(geometryColumns.getSrs());
        }catch (Exception e){
            //Use custom SpatialReferenceSystem
            SpatialReferenceSystem srs=geometryColumns.getSrs();
            String wktDefine=srs.getDefinition();
            long epsg = srs.getOrganizationCoordsysId();        
           CoordinateReferenceSystem crs= praseWKT(wktDefine);
            projection=new Projection(epsg,crs);// Projection Constructor is pravate ,I don't want to change geopackage-core source code.
        }
QGSIS can automatic recognition table [gpkg_spatial_ref_sys ] ,the field of definition
my data come from QGIS Export to Geopackage when i select a custom CRS

**Comment by bosborn** [comment]
Added custom proj4 parameter support in the geopackage-core develop branch ProjectionFactory [here](https://github.com/ngageoint/geopackage-core-java/commit/5180d2f7e7a7f55f212642e02f3bd88dfb23e62f).  The [ProjectionFactory](https://github.com/ngageoint/geopackage-core-java/blob/develop/src/main/java/mil/nga/geopackage/projection/ProjectionFactory.java).getProjection(SpatialReferenceSystem) method would need to support WKT to proj4 conversions before being very useful.  Either a license friendly or custom implementation.

**Comment by bosborn** [comment]
Refactored projections to be more custom and authority friendly, released in:
geopackage-core-java [1.3.0](https://github.com/ngageoint/geopackage-core-java/releases/tag/1.3.0)
geopackage-android [1.4.0](https://github.com/ngageoint/geopackage-android/releases/tag/1.4.0)

Not a WKT to proj4 implementation, but should provide a work around to support custom projections.

[ProjectionFactory](https://github.com/ngageoint/geopackage-core-java/blob/master/src/main/java/mil/nga/geopackage/projection/ProjectionFactory.java) will retrieve a projection in the following order:

- Check if an existing projection has been created for the authority and code
- Placeholder for an attempt to create a projection from the WKT definition, but currently a TODO
- Create a projection from parameters if provided
- Create a projection from properties, both authority config property files and runtime provided
- Create a projection from the authority:code name

The [ProjectionRetriever](https://github.com/ngageoint/geopackage-core-java/blob/master/src/main/java/mil/nga/geopackage/projection/ProjectionRetriever.java) will now allow you to set custom projections by adding them to an existing or new authority.

Here are a few examples or take a look at [this test](https://github.com/ngageoint/geopackage-core-java/blob/master/src/test/java/mil/nga/geopackage/projection/ProjectionFactoryTest.java).

Add a custom projection to the NONE authority (-1 & 0 already exist for NONE as per the GeoPackage spec):
```
ProjectionRetriever.setProjection(
   ProjectionConstants.AUTHORITY_NONE,
   100001,
   "+proj=tmerc +lat_0=0 +lon_0=121 +k=1 +x_0=500000 +y_0=0 +ellps=krass +units=m +no_defs"
);
```

Add a custom authority with multiple properties
```
Properties properties = new Properties();
properties.setProperty(String.valueOf(100001),
   "+proj=tmerc +lat_0=0 +lon_0=121 +k=1 +x_0=500000 +y_0=0 +ellps=krass +units=m +no_defs"
);
properties.setProperty(String.valueOf(100002),
   "+proj=longlat +datum=WGS84 +no_defs"
);
ProjectionRetriever.setProjections("Test", properties);
```
