### ISSUE TITLE
Support for Blobs (Feature Geometries, etc) larger than 2mb

### ISSUE THREAD

**Issue by bosborn** [ngageoint/geopackage-android#41]
Investigate using a library such as [sqlite4java](https://bitbucket.org/almworks/sqlite4java) or [a technique](https://stackoverflow.com/questions/12716859/retrieve-large-blob-from-android-sqlite-database) to support larger than 2 mb blobs for feature geometries, tile images, etc.

See ngageoint/geopackage-android-map#5.

**Comment by spyhunter99** [comment]
I was able to get org.xerial's implementation of sqlite running on android arm devices but not on x86. for what it's worth

**Comment by bosborn** [comment]
The substr approach linked in the issue is not very useful due to the fact that all values (pk, etc) come back as null, not just the blob.  I also read there is 5mb limit on this.

**Comment by bosborn** [comment]
Was able to stream blobs for rows larger than the Android supported limit.  Works with the [linked GeoPackage](http://biogeo.ucdavis.edu/data/gadm2.8/gpkg/USA_adm_gpkg.zip) in ngageoint/geopackage-android-map#5.  Large geometries take a slight performance hit for database reading, tile drawing, etc.

Will be released under version 1.4.2.  Changes include:

- Automatic blob-less requery of failed user rows (> ~2mb) followed by blob streaming
- Syncing feature indexer retrieval of near simultaneous identical row requests to improve memory usage
- Additional error handling when reading rows & geometries
- Query support for "columns as" values
- Query support from a previous query cursor result

**Comment by bosborn** [comment]
Released as part of version [2.0.0](https://github.com/ngageoint/geopackage-android/releases/tag/2.0.0).
