### ISSUE TITLE
NGA NSG PROFILE

### ISSUE THREAD

**Issue by techmavengeospatial** [ngageoint/geopackage-android#42]
Has the Android SDK been updated to support NGA NSG TILING SCHEMA/profile?

**Comment by bosborn** [comment]
Please see ngageoint/GeoPackage#4

**Comment by bosborn** [comment]
NSG is fully supported except for NGA CRS authored WKT coordinate system values.  This can be supported currently by providing those values in advance.  Will be handled automatically as part of: ngageoint/simple-features-proj-java#1
