### ISSUE TITLE
geopackage cannot open attribute table by ArcMap

### ISSUE THREAD

**Issue by polixiaohai** [ngageoint/geopackage-android#44]
Please fill out as much known and relevant information as possible.

#### Version Information:
Why did I make an error in ArcGIS through the gpkg created by Geopackage-Android and written to the data?
  * GeoPackage Android Version: 2.0.0
  * GeoPackage Android Source: 
  * Device or Emulator: 
  * Android Studio Version: 
  * Android Version Number: 
  * Android SDK Version: 26

  * Platform & OS: Android ArcGIS [10.3.1]
  * Other Relevant Libraries: 

#### Expected Results:
  * What did you expect to happen?

#### Observed Results:

  * What happened instead?
  * How often does this occur?
#### Output:

  * Any logs, errors, or output messages?

#### Steps to Reproduce:
  1. Step One
  2. Step Two
  3. ...

#### Relevant Code:

```java
// Code to reproduce the problem?
```

#### Test Files:

  * Links to any files needed for testing?

#### Additional Information:

  * Any additional configuration, data, or information that might help with the issue?

**Comment by bosborn** [comment]
Can you provide details on what you are doing?  Are you using geopackage-android to create a GeoPackage?  If so, can your provide the resulting GeoPackage file and/or code you are calling?

Are you then trying to open that in ArcGIS and getting an error?  Do you have that error or log?  If you are creating a valid GeoPackage, then you may need to direct your issue to Esri.

If the created GeoPackage is not valid, this could be a result of how the API is being called or a potential bug.

**Comment by bosborn** [comment]
If you are upgrading [this project](https://github.com/polixiaohai/OSMDroid) from geopackage-android:1.4.1 to 2.0.0, see the [warnings on the 2.0.0 major release](https://github.com/ngageoint/geopackage-android/releases/tag/2.0.0).

From [OGC](http://www.opengeospatial.org/) feedback, the constructor order was changed on BoundingBox and TileGrid.

```
* WARNING - BoundingBox.java (geopackage-core) coordinate constructor arguments order changed to (min lon, min lat, max lon, max lat)
Pre-existing calls to BoundingBox coordinate constructor should swap the min lat and max lon values
* WARNING - TileGrid.java (geopackage-core) constructor arguments order changed to (minX, minY, maxX, maxY)
Pre-existing calls to TileGrid constructor should swap the minY and maxX values
```

Try changing the arguments order to the BoundingBox constructor [in these classes](https://github.com/polixiaohai/OSMDroid/search?utf8=%E2%9C%93&q=%22import+mil.nga.geopackage.BoundingBox%22&type=).

Example:
BoundingBox boundingBox = new BoundingBox(minLon, ~~maxLon,~~ minLat, **maxLon,** maxLat);
