### ISSUE TITLE
Rebuild the index by creating a trigger

### ISSUE THREAD

**Issue by sunshine0576** [ngageoint/geopackage-android#49]
The index must be updated manually.Is there a plan to provide automatic updating index?

            // Update a Geometry 
            TestCase.assertEquals(1, featureDao.update(testFeatureRow));
            //update the index of a single feature row
            TestCase.assertTrue(featureIndexManager.index(testFeatureRow));

When I build a new Geopacakge database in QGIS, QGIS will help me create related indexes and triggers automatically.I didn't care about index maintenance when I was working, and simplified my work.

### 
CREATE TABLE "taiwan-EPSG_3857" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" LINESTRING, "ID" MEDIUMINT, "ELEV" REAL);

CREATE TRIGGER "trigger_insert_feature_count_taiwan-EPSG_3857" AFTER INSERT ON "taiwan-EPSG_3857" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count + 1 WHERE lower(table_name) = lower('taiwan-EPSG_3857'); END;

CREATE TRIGGER "rtree_taiwan-EPSG_3857_geom_update3" AFTER UPDATE ON "taiwan-EPSG_3857" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_taiwan-EPSG_3857_geom" WHERE id = OLD."fid"; INSERT OR REPLACE INTO "rtree_taiwan-EPSG_3857_geom" VALUES (NEW."fid",ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"),ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;

CREATE TRIGGER "rtree_taiwan-EPSG_3857_geom_update4" AFTER UPDATE ON "taiwan-EPSG_3857" WHEN OLD."fid" != NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_taiwan-EPSG_3857_geom" WHERE id IN (OLD."fid", NEW."fid"); END;

CREATE TRIGGER "trigger_delete_feature_count_taiwan-EPSG_3857" AFTER DELETE ON "taiwan-EPSG_3857" BEGIN UPDATE gpkg_ogr_contents SET feature_count = feature_count - 1 WHERE lower(table_name) = lower('taiwan-EPSG_3857'); END;

CREATE TRIGGER "rtree_taiwan-EPSG_3857_geom_update2" AFTER UPDATE OF "geom" ON "taiwan-EPSG_3857" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" ISNULL OR ST_IsEmpty(NEW."geom")) BEGIN DELETE FROM "rtree_taiwan-EPSG_3857_geom" WHERE id = OLD."fid"; END;

CREATE TRIGGER "rtree_taiwan-EPSG_3857_geom_delete" AFTER DELETE ON "taiwan-EPSG_3857" WHEN old."geom" NOT NULL BEGIN DELETE FROM "rtree_taiwan-EPSG_3857_geom" WHERE id = OLD."fid"; END;

CREATE TRIGGER "rtree_taiwan-EPSG_3857_geom_insert" AFTER INSERT ON "taiwan-EPSG_3857" WHEN (new."geom" NOT NULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_taiwan-EPSG_3857_geom" VALUES (NEW."fid",ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"),ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;

CREATE TRIGGER "rtree_taiwan-EPSG_3857_geom_update1" AFTER UPDATE OF "geom" ON "taiwan-EPSG_3857" WHEN OLD."fid" = NEW."fid" AND (NEW."geom" NOTNULL AND NOT ST_IsEmpty(NEW."geom")) BEGIN INSERT OR REPLACE INTO "rtree_taiwan-EPSG_3857_geom" VALUES (NEW."fid",ST_MinX(NEW."geom"), ST_MaxX(NEW."geom"),ST_MinY(NEW."geom"), ST_MaxY(NEW."geom")); END;

**Comment by sunshine0576** [comment]
This is the data I used in QGIS.

[taiwan-EPSG_3857.zip](https://github.com/ngageoint/geopackage-android/files/2423711/taiwan-EPSG_3857.zip)

**Comment by sunshine0576** [comment]
https://www.sqlite.org/rtree.html

**Comment by bosborn** [comment]
There are some RTree changes coming in the next release of [core](https://github.com/ngageoint/geopackage-core-java/compare/master...develop?expand=1) and [Android](https://github.com/ngageoint/geopackage-android/compare/master...develop?expand=1).  RTree is not supported by the the default Android SQLite library, so a dependency on the SQLite Android Bindings is being added.  The bindings still do not support user defined functions (ST_MinX, etc), so the Android RTree support will be read only.

The Feature Index Manager is getting an overhaul to support RTree, Geometry Index Extension, Metadata Index, and manual queries.

**Comment by sunshine0576** [comment]
https://www.sqlite.org/android/doc/trunk/www/install.wiki
