### ISSUE TITLE
Remove table column

### ISSUE THREAD

**Issue by osedok** [ngageoint/geopackage-android#52]
Dear Brian (@bosborn), I know there is no direct method to ALTER the table and remove the field in SQLite, but just as a curiosity - do you think of supporting this kind of operation as part of API? 

At the moment I have kind of the workaround (copy table, delete, create, insert from copy) semi working in test but If you could say what you think about this that would be great.

Kind Regards,
Andrzej

**Comment by bosborn** [comment]
You can execute raw SQL within the GeoPackage

- On user table (feature, tile, attributes) DAO, [get the connection](https://github.com/ngageoint/geopackage-core-java/blob/c72523c629195da8dc0c888877ec0e032d299f13/src/main/java/mil/nga/geopackage/user/UserCoreDao.java#L154) and [execute SQL](https://github.com/ngageoint/geopackage-core-java/blob/c72523c629195da8dc0c888877ec0e032d299f13/src/main/java/mil/nga/geopackage/db/GeoPackageCoreConnection.java#L51)
- [Execute SQL](https://github.com/ngageoint/geopackage-core-java/blob/c72523c629195da8dc0c888877ec0e032d299f13/src/main/java/mil/nga/geopackage/GeoPackageCore.java#L766) on the GeoPackage

SQLite only supports a [subset of common alter statements](https://www.sqlite.org/lang_altertable.html).  Dropping a column requires a new table (see the 12 steps under **Making Other Kinds Of Table Schema Changes**).

**Comment by osedok** [comment]
@bosborn - Yes, that is what I am doing right now. Thanks.

Regards,
Andrzej

**Comment by bosborn** [comment]
I'm not opposed to trying to support this full set of operations as an API shortcut.  We can leave this open to track the request.

**Comment by osedok** [comment]
Thanks,  creating a method on the FeatureTable object would be fantastic. Thanks for considering it. The good thing would be also to option to keep all existing nga indices and metadata for the feature layer to speed up the process for larger layers.

**Comment by sunshine0576** [comment]
SQLite 不支持删除字段,只能通过下面的方式实现
create table temp as select field1, field2, ..., from record
drop table record;    
alter table temp rename to record;

**Comment by bosborn** [comment]
I have something in progress and looking promising [here](https://github.com/ngageoint/geopackage-core-java/blob/1ef479702c9f4170bfe531cbf626fd2f9326b788/src/main/java/mil/nga/geopackage/db/AlterTable.java#L188).

**Comment by bosborn** [comment]
Released 3.3.0.  [AlterTable](https://github.com/ngageoint/geopackage-core-java/blob/3.3.0/src/main/java/mil/nga/geopackage/db/AlterTable.java) does most of the work.  You can remove user table columns [here](https://github.com/ngageoint/geopackage-core-java/blob/3.3.0/src/main/java/mil/nga/geopackage/user/UserCoreDao.java#L1847).

* Alter table support: rename table, rename column, add column, drop column, alter column, copy table
* User DAO and table alter support: add, rename, drop, alter
