### ISSUE TITLE
SQLUtils.quoteWrap is broken on Android Q beta

### ISSUE THREAD

**Issue by solcott** [ngageoint/geopackage-android#56]
#### Version Information:

  * GeoPackage Android Version: 3.2.0
  * GeoPackage Android Source: Central Repository
  * Device or Emulator: Both
  * Android Studio Version: 3.5.0-beta01
  * Android Version Number: Q beta 3
  * Android SDK Version: Q beta 3
  * Platform & OS: Q beta 3
  * Other Relevant Libraries: 

#### Expected Results:

  * What did you expect to happen?
   The returned ContentValues to be populated with the same items as the passed in ContentValues with the keys quoted

#### Observed Results:

  * What happened instead? The returned ContentValues are empty
  * How often does this occur? Every time

#### Steps to Reproduce:

  1. This is happening when trying to import a geoPackage on Android Q beta 3 using  `geoPackageManager.importGeoPackage(destinationFile, true)`

**Comment by bosborn** [comment]
Can you provide more information?
After you imported and opened the GeoPackage, what were you doing with the ContentValues?  Inserts? Updates?  Followed by a query with unexpected results?  or an error?
Most importantly, do you have or can your provide an example or a test?

**Comment by bosborn** [comment]
OK I understand the issue now...
https://issuetracker.google.com/issues/132569407

Looking into it.  Not quite sure what changed yet in Q with the createFromParcel.
[This](https://github.com/ngageoint/geopackage-android/blob/master/geopackage-sdk/src/main/java/mil/nga/geopackage/db/SQLUtils.java) was the work around to call the private map constructor since the ContentValues set methods require exact object types.

**Comment by bosborn** [comment]
Android Q must have changed something in the Parcel or ContentValues parcel parsing.  There is a good amount of language and/or deprecation discouraging non typed values.

[Changed SQLUtils](https://github.com/ngageoint/geopackage-android/blob/0f404e392e1aa6d2624b1da2a3ade93c665d53f1/geopackage-sdk/src/main/java/mil/nga/geopackage/db/SQLUtils.java#L23) to no longer use a Parcel.  There is really no great API way to copy a ContentValues with modified keys. The quote wrapping is there for GeoPackages that use non standard (but SQLite allowable) names.

Passes tests for
* compile 28, target 28, Android Q device
* compile 'android-Q', target 'Q', Android Q device
* compile 28, target 28, Android 28 device

**Comment by bosborn** [comment]
Released in [3.3.0](https://github.com/ngageoint/geopackage-android/blob/3.3.0/geopackage-sdk/src/main/java/mil/nga/geopackage/db/SQLUtils.java#L23)
