### ISSUE TITLE
Open GeoPackage file by absolute path

### ISSUE THREAD

**Issue by sveta-wl** [ngageoint/geopackage-android#57]
Hi there,

is it possible to open GeoPackage file providing an absolute path? I have some GeoPackages stored on a SD card, so I can create a simple SQLite connection to read them, but in GeoPackage Library I found only a way to provide App Context, which always takes a context.databasePath. 
Is there a way to write something like this
```
File dbFile = new File(storageDir, "myDatabase.gpkg");
GeoPackage mySdCardGeoPackage = new GeoPackage(dbFile.getAbsolutPath());
```
 or any way to provide own database connection?

#### Version Information:

  * GeoPackage Android Version: 3.2.0
  * GeoPackage Android Source: Central Repository
  * Device or Emulator: Device Nokia 6.1
  * Android Studio Version: 3.3.1
  * Android Version Number: 8.1.0

Thank you for any help.

**Comment by bosborn** [comment]
Assuming the file is externally readable (and potentially writable), have you tried [the external link imports](https://github.com/ngageoint/geopackage-android/blob/d19e9fcc636462c0f0ae1b7eca4acafae48de21b/geopackage-sdk/src/main/java/mil/nga/geopackage/GeoPackageManager.java#L560)?  The file is not copied and is read and/or modified at the external location.

**Comment by bosborn** [comment]
We did [lose the ability to open a GeoPackage on a SD card as writable a few years back](https://stackoverflow.com/questions/29562939/open-sqlitedatabase-database-on-sd-card-with-open-readwrite-access-in-android) and I never revisited it, but read only still worked.

There is currently no ability to pass in your own SQLiteDatabase connection to the GeoPackage.  Doesn't mean it could not be added, just currently not there.

**Comment by sveta-wl** [comment]
Hi @bosborn 

with external link import it works great, thank you!
