### ISSUE TITLE
FeatureDao query 

### ISSUE THREAD

**Issue by sunshine0576** [ngageoint/geopackage-android#58]
The current query method is divided into two parts. First, the index is queried, and then the data is retrieved according to ID. If there are additional supplementary queries, each data need to be judged.

    public FeatureCursor query(BoundingBox boundingBox, Projection projection, String where, String[] whereArgs) {
        String box_query =buildWhere(boundingBox, projection);
        where =box_query+"and"+where;
        return super.query(where, whereArgs);
    }

**Comment by sunshine0576** [comment]
spatialIndexClause=String.format("ROWID IN (SELECT $s FROM %s WHERE xmin < %s AND xmax > %s AND ymin < %s AND ymax > %s)",
                        indexId,indexTable,minX,maxX,minY,maxY);

**Comment by bosborn** [comment]
The bounds of the features are not stored in the [geometry columns table](https://www.geopackage.org/spec/#_geometry_columns) or the [feature table](https://www.geopackage.org/spec/#feature_user_tables).  To query on bounds, an index is needed.  The best way to query the feature table is to use the [FeatureIndexManager](https://github.com/ngageoint/geopackage-android/blob/master/geopackage-sdk/src/main/java/mil/nga/geopackage/features/index/FeatureIndexManager.java). The [default query order](https://github.com/ngageoint/geopackage-android/blob/1508dd2b07b59edbc3fa68b3e3305238d0f65497/geopackage-sdk/src/main/java/mil/nga/geopackage/features/index/FeatureIndexManager.java#L110) based upon first indexed type found: RTree, GeoPackage Index, Metadata Index, Manual.  The [results](https://github.com/ngageoint/geopackage-android/blob/master/geopackage-sdk/src/main/java/mil/nga/geopackage/features/index/FeatureIndexResults.java) can be used to iterate through the Features, in the most efficient way for each index type.  The FeatureIndexManager can also be used to index the table, however RTree in Android is currently read only.

```
String featureTable = ...
BoundingBox boundingBox = ...
Projection projection = ...

FeatureDao featureDao = geoPackage.getFeatureDao(featureTable);
FeatureIndexManager featureIndexManager = new FeatureIndexManager(activity,
                    geoPackage, featureDao);
// Or shortcut...
// FeatureIndexManager featureIndexManager = new FeatureIndexManager(activity,
                    geoPackage, featureTable);
FeatureIndexResults featureIndexResults = featureIndexManager.query(
                    boundingBox, projection);
// Or query(), query(BoundingBox), query(GeometryEnvelope)
for (FeatureRow featureRow : featureIndexResults) {
    // ...
}
featureIndexResults.close();
```

**Comment by sunshine0576** [comment]
@bosborn 
You don't understand what I'm trying to say.
select * from 【FeatureTable】where rowid in ( select rowid from 【IndexTable】 where xmin < %s AND xmax > %s AND ymin < %s AND ymax > %s )  

If additional field queries are required in addition to range queries, I just need to solve the problem through an SQL statement.
where =box_query+"and"+where;

**Comment by bosborn** [comment]
Take a look at the new [3.4.0](https://github.com/ngageoint/geopackage-android/releases/tag/3.4.0) release [API](http://ngageoint.github.io/geopackage-android/docs/api/) with added nested queries and query params (bounding box, geometry envelope, field values, where clause, where arguments)

- Feature Index Manager (handles the index choice for you) - [Source](https://github.com/ngageoint/geopackage-android/blob/3.4.0/geopackage-sdk/src/main/java/mil/nga/geopackage/features/index/FeatureIndexManager.java), [Javadoc](http://ngageoint.github.io/geopackage-android/docs/api/mil/nga/geopackage/features/index/FeatureIndexManager.html)
- RTree Index - [Source](https://github.com/ngageoint/geopackage-android/blob/3.4.0/geopackage-sdk/src/main/java/mil/nga/geopackage/extension/RTreeIndexTableDao.java), [Javadoc](http://ngageoint.github.io/geopackage-android/docs/api/mil/nga/geopackage/extension/RTreeIndexTableDao.html)
- GeoPackage Index - [Source](https://github.com/ngageoint/geopackage-android/blob/3.4.0/geopackage-sdk/src/main/java/mil/nga/geopackage/extension/index/FeatureTableIndex.java), [Javadoc](http://ngageoint.github.io/geopackage-android/docs/api/mil/nga/geopackage/extension/index/FeatureTableIndex.html)
- Metadata Index - [Source](https://github.com/ngageoint/geopackage-android/blob/3.4.0/geopackage-sdk/src/main/java/mil/nga/geopackage/db/FeatureIndexer.java), [Javadoc](http://ngageoint.github.io/geopackage-android/docs/api/mil/nga/geopackage/db/FeatureIndexer.html)
- Manual - [Source](https://github.com/ngageoint/geopackage-android/blob/3.4.0/geopackage-sdk/src/main/java/mil/nga/geopackage/features/user/ManualFeatureQuery.java), [Javadoc](http://ngageoint.github.io/geopackage-android/docs/api/mil/nga/geopackage/features/user/ManualFeatureQuery.html)
