### ISSUE TITLE
Delete External Database do not delete physical file

### ISSUE THREAD

**Issue by kttary** [ngageoint/geopackage-android#59]
If i create external database with command `manager.createAtPath(dbName, myPath)` and then delete it with `manager.delete(dbName)` i found that the physical file is not deleted. But if i create with `manager.create(dbName)` and then `manager.delete(dbName)` then the physical file is gone. Did i miss some setup? I'm still using geopackage android 3.2.0. Thank you

**Comment by bosborn** [comment]
GeoPackages through external links are not managed in the app's memory space.  Upon deletion, a GeoPackage internal to the app's memory space is deleted.  However for an externally linked GeoPackage where the file exists outside of the app's memory space, only the link to the GeoPackage is deleted.  The same thing would happen if you deleted the app.

When the file path is provided, the GeoPackage is treated as external.

External Creation Methods:
* createAtPath(String database, File path)
* createFile(File file)
* createFile(String database, File file)
* importGeoPackageAsExternalLink(File path, String database)
* importGeoPackageAsExternalLink(File path, String database, boolean override)
* importGeoPackageAsExternalLink(String path, String database)
* importGeoPackageAsExternalLink(String path, String database, boolean override)

There are a number of external related methods to determine if a GeoPackager is external.  For those, you could try delete the file on your own assuming your app has write access.
* isExternal(String database)
* existsAtExternalFile(File file)
* existsAtExternalPath(String path)
* getPath(String database)
* getFile(String database)
* getDatabaseAtExternalFile(File file)
* getDatabaseAtExternalPath(String path)

**Comment by bosborn** [comment]
Also, if you would like to import / copy the GeoPackage internally into the app space memory:
* importGeoPackage(File file, boolean override)
* importGeoPackage(String database, InputStream stream)
* importGeoPackage(String database, InputStream stream, GeoPackageProgress progress)
* importGeoPackage(String database, InputStream stream, boolean override)
* importGeoPackage(String database, InputStream stream, boolean override, GeoPackageProgress progress)
* importGeoPackage(String name, File file)
* importGeoPackage(String name, File file, boolean override)
* importGeoPackage(String name, URL url)
* importGeoPackage(String name, URL url, GeoPackageProgress progress)
* importGeoPackage(String name, URL url, boolean override)
* importGeoPackage(String name, URL url, boolean override, GeoPackageProgress progress)
