### ISSUE TITLE
RTree Index 3.4.0 

### ISSUE THREAD

**Issue by osedok** [ngageoint/geopackage-android#60]
**State your question**
Hi Brian, would you kindly provide more clarification around Line 433 (comment)  in https://github.com/ngageoint/geopackage-android/blob/3.4.0/geopackage-sdk/src/main/java/mil/nga/geopackage/features/index/FeatureIndexManager.java:

                case RTREE:
                // Updated by triggers, ignore for RTree
                indexed = true;

Is the rtree index updated when new feature is being added to the table?

**Additional context**
Is now rtree index supported for writing?

Thanks you,
Kind Regards,
Andrzej

**Comment by bosborn** [comment]
Sorry, RTree is still not available for writing in Android.  That is a copy and paste from the Java implementation / placeholder for Android.  I [published](https://search.maven.org/artifact/mil.nga/sqlite-android/3300100/aar) and upgraded to the [latest](https://sqlite.org/download.html) Android SQLite Bindings, but User defined functions [are still not supported](https://www.sqlite.org/android/artifact?udc=1&ln=on&name=afd8e719c44fb86f) (line 250: // TODO: Support functions that return values.).

**Comment by osedok** [comment]
Thank you for clarification  Brian (@bosborn), this is the answer I have expected.
