### ISSUE TITLE
Does the GeoPackage Native Library support converting vector data to GPKG vector features?

### ISSUE THREAD

**Issue by geospatialmapmashup** [ngageoint/geopackage-android#63]
**State your question**
Does the GeoPackage Native Library support converting vector data to GPKG vector features?

**Additional context**
I've been reviewing the classes and methods and I am having issues finding if the GeoPackage-Android supports converting SHP or GeoJSON or data into GPKG vector features like GeoPackage-JS can do.

**Comment by bosborn** [comment]
Conversions can be done with the [Simple Features](https://github.com/ngageoint/simple-features-java) library dependencies ( [WKB](https://github.com/ngageoint/simple-features-wkb-java), [GeoJSON](https://github.com/ngageoint/simple-features-geojson-java), [Projection](https://github.com/ngageoint/simple-features-proj-java), [OGC API Features JSON](https://github.com/ngageoint/ogc-api-features-json-java) ).  As long as features can be converted to WKB, this library can add the GeoPackage header bytes.  There is currently no included SHP conversion.

See ngageoint/geopackage-android-map#16 for some examples including GeoJSON.
