### ISSUE TITLE
How to create a custom SpatialReference?

### ISSUE THREAD

**Issue by anwz0611** [ngageoint/geopackage-android#64]
How to create a custom SpatialReference?
When I try to create a custom  SpatialReference.   Throw the wrong ：
mil.nga.sf.util.SFException: Failed to create projection for authority
thanks

**Comment by bosborn** [comment]
I assume you resolved your issue, but just in case.

An [example of creating a custom SRS](https://github.com/ngageoint/geopackage-android/blob/134d0ddd1074f4de11b87ef8112530105f95f6ff/geopackage-sdk/src/androidTest/java/mil/nga/geopackage/test/srs/SpatialReferenceSystemUtils.java#L343)

If you want to use a projection for custom SRS as indicated by the error, [you can add custom projections](https://github.com/ngageoint/simple-features-proj-java/blob/c736e7b78bfa51de0f163875d6af5eed1b0df01b/src/test/java/mil/nga/sf/proj/ProjectionFactoryTest.java#L23). By default, there is built in authority support for epsg, ogc, and none.
